import{a as L,S as v,i as n}from"./assets/vendor-6e0bf343.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const w="43233565-271a1074870da79dda90f0013",S="https://pixabay.com/api/";async function f(r,e){try{return(await L.get(S,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch(s){console.error(s)}}function g(r){return r.map(e=>`<li class="gallery-item">
                <a class="gallery-link" href='${e.largeImageURL}'>
                  <img class="gallery-image" src='${e.webformatURL}' alt='${e.tags}' />
                </a>
                <div class="stats">
                  <p><span>Likes</span>${e.likes}</p>
                  <p><span>Views</span>${e.views}</p>
                  <p><span>Comments</span>${e.comments}</p>
                  <p><span>Downloads</span>${e.downloads}</p>
                </div>
              </li>`).join("")}const b=document.querySelector(".form"),d=document.querySelector(".gallery"),h=document.querySelector(".loader"),c=document.querySelector(".load-more");let a=1,i="";c.addEventListener("click",P);b.addEventListener("submit",q);const y=new v(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7});async function q(r){if(r.preventDefault(),c.classList.add("is-hidden"),m(),d.innerHTML="",a=1,i=r.target.queryInput.value,i!==""){try{const e=await f(i,a);if(e.hits.length===0)return n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});d.innerHTML=g(e.hits),y.refresh(),e.total>15&&c.classList.remove("is-hidden"),r.target.queryInput.value=""}catch(e){n.error({message:`Ups... ${e}`,position:"topRight"})}p()}else p(),n.error({message:"Please, enter a word",position:"topRight"})}async function P(){m(),a+=1;try{const r=await f(i,a),e=Math.ceil(r.total/15);d.insertAdjacentHTML("beforeend",g(r.hits)),y.refresh();const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),e===a&&(c.classList.add("is-hidden"),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}))}catch(r){console.log(r)}p()}function m(){h.classList.remove("is-hidden")}function p(){h.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
