import{a as m,S as L,i as n}from"./assets/vendor-6e0bf343.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const v="43233565-271a1074870da79dda90f0013",w="https://pixabay.com/api/";async function p(r,e){try{return(await m.get(w,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch(o){console.error(o)}}function f(r){return r.map(e=>`<li class="gallery-item">
                <a class="gallery-link" href='${e.largeImageURL}'>
                  <img class="gallery-image" src='${e.webformatURL}' alt='${e.tags}' />
                </a>
                <div class="stats">
                  <p><span>Likes</span>${e.likes}</p>
                  <p><span>Views</span>${e.views}</p>
                  <p><span>Comments</span>${e.comments}</p>
                  <p><span>Downloads</span>${e.downloads}</p>
                </div>
              </li>`).join("")}const S=document.querySelector(".form"),l=document.querySelector(".gallery"),g=document.querySelector(".loader"),i=document.querySelector(".load-more");let a=1,b="";i.addEventListener("click",P);S.addEventListener("submit",q);const h=new L(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7});async function q(r){r.preventDefault(),i.classList.add("is-hidden"),y(),l.innerHTML="",a=1;const e=r.target.queryInput.value;if(e!==""){try{const o=await p(e,a);if(o.hits.length===0)return n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});l.innerHTML=f(o.hits),h.refresh(),o.total>15&&i.classList.remove("is-hidden"),r.target.queryInput.value=""}catch(o){n.error({message:`Ups... ${o}`,position:"topRight"})}d()}else d(),n.error({message:"Please, enter a word",position:"topRight"})}async function P(){y(),a+=1;try{const r=await p(b,a),e=Math.ceil(r.total/15);l.insertAdjacentHTML("beforeend",f(r.hits)),h.refresh();const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),e===a&&(i.classList.add(".is-hidden"),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}))}catch(r){console.log(r)}d()}function y(){g.classList.remove("is-hidden")}function d(){g.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
